### ISSUE TITLE
how to set bigger width?

### ISSUE THREAD

**Issue by demiro** [footageone/angular-material-addons#20]
So, if I add a custom option to it like this:

`{ panelClass: 'side-right-panel' }`

and set the width to 550px in my css like this:

.side-right-panel{
with: 550px !important;
}

it is not working... the parent .cdk-overlay-pane gets assigned 420px...

so how do I do it? how can I have wider pane?

**Comment by demiro** [comment]
I did the changes, would like to push and create a PR, how do I do it?

**Comment by DaSchTour** [comment]
Have you created a fork of this repo? Then you can push it to the fork and the create a PR from there. Please take a look at the github help: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ErangaRavindu** [comment]
Issue is still there...

**Comment by DaSchTour** [comment]
You can set it bigger by using width in the configuration object.
