### ISSUE TITLE
NullInjectorError

### ISSUE THREAD

**Issue by rinella** [footageone/angular-material-addons#44]
![Screen Shot 2020-05-30 at 5 25 06 PM](https://user-images.githubusercontent.com/9531567/83339315-a085ad80-a29a-11ea-8465-039f894b60b5.png)

import { MatRightSheet } from 'mat-right-sheet';

  constructor(
    private rightSheet: MatRightSheet) {
  }

**Comment by rinella** [comment]
Not sure if it is a bug or I am doing it wrong.  Do you have an example I can follow?  I installed via npm.

**Comment by DaSchTour** [comment]
Did you import the MatRightSheetModule? Actually everything should work as with MatBottomSheet

**Comment by rinella** [comment]
Yes,  I imported in the modules file.  I actually installed matbottomsheet after I looked at the source code and noticed the code was almost exactly like matbottomsheet.  I will fork and show you the code.

**Comment by DaSchTour** [comment]
Yes. This is a copy of matBottomSheet and works in the same way. It would already help if you could show the message from a not minified version so that one can see what really is missing. From the uk -> e it's only wild guessing.
