### ISSUE TITLE
How to set a responsive width?

### ISSUE THREAD

**Issue by ErangaRavindu** [footageone/angular-material-addons#51]
Hi, I want to make width responsive, according to the screen size. how can i do that?

**Comment by DaSchTour** [comment]
You can use viewport sizes (vw or vh) https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
on the width config
https://github.com/footageone/angular-material-addons/blob/521dac7f5fd498d95ea231548f1e4345f2bee834/projects/right-sheet/src/lib/right-sheet.config.ts#L69

**Comment by ErangaRavindu** [comment]
Is there anyway that ican do it by using a class. I want to use media queries.
Ex-: ipad width 100%, desktop: 50% that how i want it to be. current im doing that by ts.

**Comment by DaSchTour** [comment]
I think you can add an own class by using panelClass property.

**Comment by mrmokwa** [comment]
@ErangaRavindu did get your example working? How did you achieve it?
