### ISSUE TITLE
Sync with official bottom-sheet changes - ChangeDetection bug

### ISSUE THREAD

**Issue by vyrotek** [footageone/angular-material-addons#54]
I found that component state changes weren't being detected in both right-sheet and the official bottom-sheet.

A bug was submitted and a PR change has been created to address the issue.
https://github.com/angular/components/pull/21175

I've created this PR to apply the same change from bottom-sheet to right-sheet.
https://github.com/footageone/angular-material-addons/pull/53

**Comment by vyrotek** [comment]
Looks like it was merged.

**Comment by vyrotek** [comment]
Angular has released their fix in [11.0.2](https://github.com/angular/components/releases/tag/11.0.2)

@DaSchTour Any chance we can get this merged and published as well?

**Comment by DaSchTour** [comment]
Is merged and published in version 3.0.2
