### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by DCh06** [footageone/angular-material-addons#84]
Issue:
 In readme

"@include mat-right-sheet-theme($theme);" and "@include mat-right-sheet-typography($custom-typography);" are undefined mixins.

Should be : "@include right-sheet-theme($theme);" and "@include right-sheet-typography($custom-typography);"

**Comment by duxor** [comment]
@DCh06 @DaSchTour Seems that someone makes a build for the latest release from the uncommitted changes... The code on the master branch is in sync with the docs.
